apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsse
  namespace: demo-system
  labels:
    app: "eventsse"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "eventsse"
  template:
    metadata:
      labels:
        app: "eventsse"
    spec:
      serviceAccountName: eventsse
      volumes:
        - emptyDir: {}
          name: tmp-dir
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.12
      - name: eventsse
        image: kind.local/eventsse:latest
        imagePullPolicy: Never
        args:
        - --etcd-servers=http://localhost:2379
        - --dump-env=true
        - --debug=true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
        ports:
        - containerPort: 8181
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
    